/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Palette is variable-driven so the whole app themes at once —
        // see the token block at the top of src/index.css.
        // `white` is deliberately NOT themed: it is the text colour on every
        // coloured button and the overlay tint on dark chrome, and both must
        // stay white in both themes. Panels use `surface`.
        canvas:  "rgb(var(--c-canvas) / <alpha-value>)",
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        // One step above `surface` — nested panels, table headers, inputs
        // sitting on a card.
        "surface-2": "rgb(var(--c-surface-2) / <alpha-value>)",
        gray: {
          50: "rgb(var(--c-gray-50) / <alpha-value>)",
          100: "rgb(var(--c-gray-100) / <alpha-value>)",
          200: "rgb(var(--c-gray-200) / <alpha-value>)",
          300: "rgb(var(--c-gray-300) / <alpha-value>)",
          400: "rgb(var(--c-gray-400) / <alpha-value>)",
          500: "rgb(var(--c-gray-500) / <alpha-value>)",
          600: "rgb(var(--c-gray-600) / <alpha-value>)",
          700: "rgb(var(--c-gray-700) / <alpha-value>)",
          800: "rgb(var(--c-gray-800) / <alpha-value>)",
          900: "rgb(var(--c-gray-900) / <alpha-value>)",
          950: "rgb(var(--c-gray-950) / <alpha-value>)",
        },
        emerald: {
          50: "rgb(var(--c-emerald-50) / <alpha-value>)",
          100: "rgb(var(--c-emerald-100) / <alpha-value>)",
          200: "rgb(var(--c-emerald-200) / <alpha-value>)",
          300: "rgb(var(--c-emerald-300) / <alpha-value>)",
          400: "rgb(var(--c-emerald-400) / <alpha-value>)",
          500: "rgb(var(--c-emerald-500) / <alpha-value>)",
          600: "rgb(var(--c-emerald-600) / <alpha-value>)",
          700: "rgb(var(--c-emerald-700) / <alpha-value>)",
          800: "rgb(var(--c-emerald-800) / <alpha-value>)",
          900: "rgb(var(--c-emerald-900) / <alpha-value>)",
        },
        red: {
          50: "rgb(var(--c-red-50) / <alpha-value>)",
          100: "rgb(var(--c-red-100) / <alpha-value>)",
          200: "rgb(var(--c-red-200) / <alpha-value>)",
          300: "rgb(var(--c-red-300) / <alpha-value>)",
          400: "rgb(var(--c-red-400) / <alpha-value>)",
          500: "rgb(var(--c-red-500) / <alpha-value>)",
          600: "rgb(var(--c-red-600) / <alpha-value>)",
          700: "rgb(var(--c-red-700) / <alpha-value>)",
          800: "rgb(var(--c-red-800) / <alpha-value>)",
          900: "rgb(var(--c-red-900) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--c-amber-50) / <alpha-value>)",
          100: "rgb(var(--c-amber-100) / <alpha-value>)",
          200: "rgb(var(--c-amber-200) / <alpha-value>)",
          300: "rgb(var(--c-amber-300) / <alpha-value>)",
          400: "rgb(var(--c-amber-400) / <alpha-value>)",
          500: "rgb(var(--c-amber-500) / <alpha-value>)",
          600: "rgb(var(--c-amber-600) / <alpha-value>)",
          700: "rgb(var(--c-amber-700) / <alpha-value>)",
          800: "rgb(var(--c-amber-800) / <alpha-value>)",
          900: "rgb(var(--c-amber-900) / <alpha-value>)",
        },
        yellow: {
          50: "rgb(var(--c-yellow-50) / <alpha-value>)",
          100: "rgb(var(--c-yellow-100) / <alpha-value>)",
          200: "rgb(var(--c-yellow-200) / <alpha-value>)",
          300: "rgb(var(--c-yellow-300) / <alpha-value>)",
          400: "rgb(var(--c-yellow-400) / <alpha-value>)",
          500: "rgb(var(--c-yellow-500) / <alpha-value>)",
          600: "rgb(var(--c-yellow-600) / <alpha-value>)",
          700: "rgb(var(--c-yellow-700) / <alpha-value>)",
          800: "rgb(var(--c-yellow-800) / <alpha-value>)",
          900: "rgb(var(--c-yellow-900) / <alpha-value>)",
        },
        green: {
          50: "rgb(var(--c-green-50) / <alpha-value>)",
          100: "rgb(var(--c-green-100) / <alpha-value>)",
          200: "rgb(var(--c-green-200) / <alpha-value>)",
          300: "rgb(var(--c-green-300) / <alpha-value>)",
          400: "rgb(var(--c-green-400) / <alpha-value>)",
          500: "rgb(var(--c-green-500) / <alpha-value>)",
          600: "rgb(var(--c-green-600) / <alpha-value>)",
          700: "rgb(var(--c-green-700) / <alpha-value>)",
          800: "rgb(var(--c-green-800) / <alpha-value>)",
          900: "rgb(var(--c-green-900) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--c-blue-50) / <alpha-value>)",
          100: "rgb(var(--c-blue-100) / <alpha-value>)",
          200: "rgb(var(--c-blue-200) / <alpha-value>)",
          300: "rgb(var(--c-blue-300) / <alpha-value>)",
          400: "rgb(var(--c-blue-400) / <alpha-value>)",
          500: "rgb(var(--c-blue-500) / <alpha-value>)",
          600: "rgb(var(--c-blue-600) / <alpha-value>)",
          700: "rgb(var(--c-blue-700) / <alpha-value>)",
          800: "rgb(var(--c-blue-800) / <alpha-value>)",
          900: "rgb(var(--c-blue-900) / <alpha-value>)",
        },
        sky: {
          50: "rgb(var(--c-sky-50) / <alpha-value>)",
          100: "rgb(var(--c-sky-100) / <alpha-value>)",
          200: "rgb(var(--c-sky-200) / <alpha-value>)",
          300: "rgb(var(--c-sky-300) / <alpha-value>)",
          400: "rgb(var(--c-sky-400) / <alpha-value>)",
          500: "rgb(var(--c-sky-500) / <alpha-value>)",
          600: "rgb(var(--c-sky-600) / <alpha-value>)",
          700: "rgb(var(--c-sky-700) / <alpha-value>)",
          800: "rgb(var(--c-sky-800) / <alpha-value>)",
          900: "rgb(var(--c-sky-900) / <alpha-value>)",
        },
        indigo: {
          50: "rgb(var(--c-indigo-50) / <alpha-value>)",
          100: "rgb(var(--c-indigo-100) / <alpha-value>)",
          200: "rgb(var(--c-indigo-200) / <alpha-value>)",
          300: "rgb(var(--c-indigo-300) / <alpha-value>)",
          400: "rgb(var(--c-indigo-400) / <alpha-value>)",
          500: "rgb(var(--c-indigo-500) / <alpha-value>)",
          600: "rgb(var(--c-indigo-600) / <alpha-value>)",
          700: "rgb(var(--c-indigo-700) / <alpha-value>)",
          800: "rgb(var(--c-indigo-800) / <alpha-value>)",
          900: "rgb(var(--c-indigo-900) / <alpha-value>)",
        },
        violet: {
          50: "rgb(var(--c-violet-50) / <alpha-value>)",
          100: "rgb(var(--c-violet-100) / <alpha-value>)",
          200: "rgb(var(--c-violet-200) / <alpha-value>)",
          300: "rgb(var(--c-violet-300) / <alpha-value>)",
          400: "rgb(var(--c-violet-400) / <alpha-value>)",
          500: "rgb(var(--c-violet-500) / <alpha-value>)",
          600: "rgb(var(--c-violet-600) / <alpha-value>)",
          700: "rgb(var(--c-violet-700) / <alpha-value>)",
          800: "rgb(var(--c-violet-800) / <alpha-value>)",
          900: "rgb(var(--c-violet-900) / <alpha-value>)",
        },
        purple: {
          50: "rgb(var(--c-purple-50) / <alpha-value>)",
          100: "rgb(var(--c-purple-100) / <alpha-value>)",
          200: "rgb(var(--c-purple-200) / <alpha-value>)",
          300: "rgb(var(--c-purple-300) / <alpha-value>)",
          400: "rgb(var(--c-purple-400) / <alpha-value>)",
          500: "rgb(var(--c-purple-500) / <alpha-value>)",
          600: "rgb(var(--c-purple-600) / <alpha-value>)",
          700: "rgb(var(--c-purple-700) / <alpha-value>)",
          800: "rgb(var(--c-purple-800) / <alpha-value>)",
          900: "rgb(var(--c-purple-900) / <alpha-value>)",
        },
        orange: {
          50: "rgb(var(--c-orange-50) / <alpha-value>)",
          100: "rgb(var(--c-orange-100) / <alpha-value>)",
          200: "rgb(var(--c-orange-200) / <alpha-value>)",
          300: "rgb(var(--c-orange-300) / <alpha-value>)",
          400: "rgb(var(--c-orange-400) / <alpha-value>)",
          500: "rgb(var(--c-orange-500) / <alpha-value>)",
          600: "rgb(var(--c-orange-600) / <alpha-value>)",
          700: "rgb(var(--c-orange-700) / <alpha-value>)",
          800: "rgb(var(--c-orange-800) / <alpha-value>)",
          900: "rgb(var(--c-orange-900) / <alpha-value>)",
        },
        brand: {
          50: "rgb(var(--c-brand-50) / <alpha-value>)",
          100: "rgb(var(--c-brand-100) / <alpha-value>)",
          200: "rgb(var(--c-brand-200) / <alpha-value>)",
          300: "rgb(var(--c-brand-300) / <alpha-value>)",
          400: "rgb(var(--c-brand-400) / <alpha-value>)",
          500: "rgb(var(--c-brand-500) / <alpha-value>)",
          600: "rgb(var(--c-brand-600) / <alpha-value>)",
          700: "rgb(var(--c-brand-700) / <alpha-value>)",
          800: "rgb(var(--c-brand-800) / <alpha-value>)",
          900: "rgb(var(--c-brand-900) / <alpha-value>)",
        },
        // CTA — warm orange, reserved for primary conversion actions only
        // ("New assistant", "Create workspace", "Upgrade").
        cta: {
          50:  "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
        },
        // Ink — the chrome scale (sidebar, top bar, headings). Fixed rather
        // than themed: the console's chrome stays dark in both themes, the way
        // it does in the product this mirrors.
        ink: {
          DEFAULT: "#05080a",
          950: "#05080a",
          900: "#0a1012",
          800: "#111a1c",
          700: "#1b2628",
        },
      },
      fontFamily: {
        sans: ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      borderRadius: {
        xl:  "0.875rem",
        "2xl": "1.25rem",
        "3xl": "1.75rem",
      },
      boxShadow: {
        // Soft, layered elevation — subtle at rest, a touch more on hover.
        xs:    "0 1px 2px 0 rgba(10,10,15,0.05)",
        card:  "0 1px 2px rgba(10,10,15,0.04), 0 1px 3px rgba(10,10,15,0.06)",
        pop:   "0 4px 12px rgba(10,10,15,0.08), 0 2px 4px rgba(10,10,15,0.04)",
        modal: "0 16px 48px rgba(10,10,15,0.16), 0 4px 12px rgba(10,10,15,0.08)",
        // Colored ambient lift — used on card/row hover for the "alive" feel.
        lift:  "0 12px 24px -8px rgba(13,148,136,0.18), 0 4px 8px rgba(10,10,15,0.06)",
        "glow-cta": "0 8px 20px -6px rgba(234,88,12,0.35)",
      },
      backgroundImage: {
        "mesh-light": "radial-gradient(at 15% 20%, rgba(94,234,212,0.25) 0, transparent 50%), radial-gradient(at 85% 15%, rgba(196,181,253,0.22) 0, transparent 50%), radial-gradient(at 50% 85%, rgba(253,186,186,0.18) 0, transparent 55%)",
        "mesh-navy":  "radial-gradient(at 20% 15%, rgba(20,184,166,0.16) 0, transparent 45%), radial-gradient(at 80% 80%, rgba(124,58,237,0.10) 0, transparent 50%)",
      },
      keyframes: {
        shimmer: {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition:  "200% 0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "translateY(6px) scale(0.98)" },
          to:   { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "mesh-drift": {
          "0%, 100%": { backgroundPosition: "0% 0%, 100% 0%, 50% 100%" },
          "50%":      { backgroundPosition: "20% 10%, 80% 20%, 40% 90%" },
        },
      },
      animation: {
        shimmer:     "shimmer 1.5s ease-in-out infinite",
        "fade-in":   "fade-in 0.18s ease-out",
        "slide-up":  "slide-up 0.24s cubic-bezier(0.16,1,0.3,1)",
        "scale-in":  "scale-in 0.18s cubic-bezier(0.16,1,0.3,1)",
        "mesh-drift": "mesh-drift 24s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
